sudo: false
language: node_js
node_js:
  - 9
  - 8
  - 6
after_success:
  - cat ./coverage/coverage.json | ./node_modules/.bin/adana -F adana-format-istanbul > ./coverage/istanbul.json
  - bash <(curl -s https://codecov.io/bash) -f ./coverage/istanbul.json
