// flow-typed signature: 170c746f7653633b7e0f41dbde695b2b
// flow-typed version: <<STUB>>/backo_v^1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'backo' {
  declare module.exports: any;
}
