// flow-typed signature: 4a60d5167d82ce43fa1f96f92689f08c
// flow-typed version: <<STUB>>/chokidar_v^2.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chokidar' {
  declare module.exports: any;
}
