// flow-typed signature: fa972c08735dbd558ed4eb6a0ec0adf5
// flow-typed version: <<STUB>>/import-file_v^1.2.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-file' {
  declare module.exports: any;
}
