// flow-typed signature: 0649f2db1776e5b63954e8c1a6d4a292
// flow-typed version: <<STUB>>/memory-fs_v^0.4.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memory-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memory-fs' {
  declare module.exports: any;
}
