// flow-typed signature: 4fe18e61079747f396a108083d5c8779
// flow-typed version: <<STUB>>/mime-types_v^2.1.14/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mime-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mime-types' {
  declare module.exports: any;
}
