// flow-typed signature: ce48790296e834cc7e4fefb2e2e9cbfa
// flow-typed version: <<STUB>>/open_v^0.0.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open' {
  declare module.exports: any;
}
