// flow-typed signature: fd2162c2f79b708c6b465b5d1a8c6654
// flow-typed version: <<STUB>>/openport_v0.0.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openport' {
  declare module.exports: any;
}
