// flow-typed signature: 642259f43c120e39227a346cb54bf9f1
// flow-typed version: <<STUB>>/redux-observers_v^2.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-observers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-observers' {
  declare module.exports: any;
}
