// flow-typed signature: e13044fd3918def1025501305eba4029
// flow-typed version: <<STUB>>/webpack_v4.0.0-beta.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}

declare module 'webpack/lib/Stats' {
  declare module.exports: any;
}
