// flow-typed signature: a301a8e170fefa93ade0de767a93d832
// flow-typed version: <<STUB>>/ws_v^4.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {
  declare module.exports: any;
}
